### PR TITLE
Update to API version 1.0

### LINKED ISSUE #7: Version 1.0
Your plugin is not compatible any longer with the current version of VCV Rack. Are you planning on updating it and releasing a new version?

### PR DESCRIPTION
**Pull request by chuckhousley**
Closes #7 
I wanted to use your modules so I took the time to update them.

### CODE REVIEW

**Comment by JTriggerFish** [comment]
This is awesome !
Thanks a lot for doing this - been wanting to do it but haven’t found the time.
Let me take a look at the merge conflicts this morning.

**Comment by JTriggerFish** [comment]
Have I missed something in the merge ? Doesn’t seem to build on v1

**Comment by chuckhousley** [comment]
I went to bed after I submitted, I'll take a look in a second

**Comment by chuckhousley** [comment]
The linux build worked fine but the mac build doesn't seem to be finding the updated SDK.  I think the plugin library maintainers build on linux anyway but I'll still get a mac dev environment going sometime today and I'll see if it's something environment specific.

**Comment by JTriggerFish** [comment]
Cheers, will see if I can try it on Mac too.
Believe it or not my windows dev laptop had a hard drive failure while I tried to build this morning, and I then went to grab by old MacBook Air just to find the battery I replaced a couple of months ago had died too...

**Comment by chuckhousley** [comment]
Oh dang, that sucks. I pulled my old Mac mini out and the install for
Catalina is going to be at least 3 hours so I may not actually get around
to it today.

**Comment by JTriggerFish** [comment]
It builds fine on a local Mojave box, and seems to load fine.
Will have to figure out how to fix the Travis build but I think it's good to release.
Thanks again for updating, really appreciate it.

**Pull request merged**
